[package]
name = "tibber-dashboard"
version = "0.1.0"
authors = ["Albert <mail@albertskog.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "0.6.0"
embedded-graphics-simulator = "0.2.0"