FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

COPY target/armv7-unknown-linux-gnueabihf/debug/tibber-dashboard .

CMD modprobe i2c-dev && ./tibber-dashboard
